backend:
  name: github
  repo: DRIMchansky/drimchansky.ru

media_folder: static/assets
public_folder: /assets

collections:
  - name: works
    label: Works
    folder: src/data/works
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
